package com.rodrigoguerrero.mynotes.theme.colors

import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

val dark_primary = Color(0xFF3DDAE7)
val dark_onPrimary = Color(0xFF00363B)
val dark_primaryContainer = Color(0xFF004F55)
val dark_onPrimaryContainer = Color(0xFF80F4FF)
val dark_secondary = Color(0xFFB1CBCE)
val dark_onSecondary = Color(0xFF1B3437)
val dark_secondaryContainer = Color(0xFF324B4D)
val dark_onSecondaryContainer = Color(0xFFCCE8EA)
val dark_tertiary = Color(0xFFB7C7EA)
val dark_onTertiary = Color(0xFF21304C)
val dark_tertiaryContainer = Color(0xFF384764)
val dark_onTertiaryContainer = Color(0xFFD7E2FF)
val dark_error = Color(0xFFFFB4AB)
val dark_errorContainer = Color(0xFF93000A)
val dark_onError = Color(0xFF690005)
val dark_onErrorContainer = Color(0xFFFFDAD6)
val dark_background = Color(0xFF191C1D)
val dark_onBackground = Color(0xFFE0E3E3)
val dark_surface = Color(0xFF191C1D)
val dark_onSurface = Color(0xFFE0E3E3)
val dark_surfaceVariant = Color(0xFF3F4849)
val dark_onSurfaceVariant = Color(0xFFBEC8C9)
val dark_outline = Color(0xFF899393)
val dark_inverseOnSurface = Color(0xFF191C1D)
val dark_inverseSurface = Color(0xFFE0E3E3)
val dark_inversePrimary = Color(0xFF006970)
val dark_shadow = Color(0xFF000000)
val dark_surfaceTint = Color(0xFF3DDAE7)
val dark_outlineVariant = Color(0xFF3F4849)
val dark_scrim = Color(0xFF000000)

val light_primary = Color(0xFF006970)
val light_onPrimary = Color(0xFFFFFFFF)
val light_primaryContainer = Color(0xFF80F4FF)
val light_onPrimaryContainer = Color(0xFF002022)
val light_secondary = Color(0xFF4A6365)
val light_onSecondary = Color(0xFFFFFFFF)
val light_secondaryContainer = Color(0xFFCCE8EA)
val light_onSecondaryContainer = Color(0xFF051F22)
val light_tertiary = Color(0xFF505E7D)
val light_onTertiary = Color(0xFFFFFFFF)
val light_tertiaryContainer = Color(0xFFD7E2FF)
val light_onTertiaryContainer = Color(0xFF0B1B36)
val light_error = Color(0xFFBA1A1A)
val light_errorContainer = Color(0xFFFFDAD6)
val light_onError = Color(0xFFFFFFFF)
val light_onErrorContainer = Color(0xFF410002)
val light_background = Color(0xFFFAFDFD)
val light_onBackground = Color(0xFF191C1D)
val light_surface = Color(0xFFFAFDFD)
val light_onSurface = Color(0xFF191C1D)
val light_surfaceVariant = Color(0xFFDAE4E5)
val light_onSurfaceVariant = Color(0xFF3F4849)
val light_outline = Color(0xFF6F797A)
val light_inverseOnSurface = Color(0xFFEFF1F1)
val light_inverseSurface = Color(0xFF2D3131)
val light_inversePrimary = Color(0xFF3DDAE7)
val light_shadow = Color(0xFF000000)
val light_surfaceTint = Color(0xFF006970)
val light_outlineVariant = Color(0xFFBEC8C9)
val light_scrim = Color(0xFF000000)

val seed = Color(0xFF00C3D0)

val LocalMyNotesColors = staticCompositionLocalOf { lightColors() }
